name: Daily Save

on: [push]

jobs:
    Daily-Save:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4  
            - name: Install Dependencies
              run: pip install -r requirements.txt
            - name: Run Save
              run: python app.py